#!/usr/bin/env bash

# Install WordPress.
wp core install \
  --title="Wordpress Plugin Template" \
  --admin_user="wordpress" \
  --admin_password="wordpress" \
  --admin_email="admin@example.com" \
  --url="http://lvh.me" \
  --skip-email

# Update Permalink Structure
wp option update permalink_structure "/%year%/%monthnum%/%postname%/" --skip-themes --skip-plugins

# Activate Plugin
wp plugin activate yourplugin